version: "3.9"

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - ${APPLICATION_PORT}:8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: