# Generated by Django 5.2.4 on 2025-09-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='authentication.organization'),
        ),
    ]
