# Generated by Django 5.2.4 on 2025-09-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_publicapikey_secretapikey_delete_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretapikey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='secretapikey',
            name='organization',
        ),
        migrations.DeleteModel(
            name='PublicAPIKey',
        ),
        migrations.DeleteModel(
            name='SecretAPIKey',
        ),
    ]
