# Generated by Django 5.2.4 on 2025-09-13 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_organization_country_organization_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('key_type', models.CharField(choices=[('secret', 'Secret Key'), ('public', 'Public Key')], max_length=10)),
                ('key_id', models.CharField(max_length=50, unique=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='authentication.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['key_id'], name='authenticat_key_id_4e6fe4_idx'), models.Index(fields=['organization', 'key_type'], name='authenticat_organiz_c9a805_idx')],
                'unique_together': {('organization', 'key_type')},
            },
        ),
    ]
