# Generated by Django 5.2.4 on 2025-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
