# Generated by Django 5.2.4 on 2025-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_apikey_sandbox_organization_is_sandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('auditor', 'Auditor'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('support_agent', 'Support Agent'), ('developer', 'Developer')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('auditor', 'Auditor'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('support_agent', 'Support Agent'), ('developer', 'Developer')], default='member', max_length=20),
        ),
    ]
