# Generated by Django 5.2.6 on 2025-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_organization_is_sandbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="sandbox",
            field=models.BooleanField(default=False),
        ),
    ]
