# Generated by Django 5.2.4 on 2025-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_state',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='test', max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('account_verification', 'Account Verification'), ('two_factor_auth', 'Two Factor Authentication')], max_length=20),
        ),
    ]
