# Generated by Django 5.2.4 on 2025-09-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_organization_is_verified_user_display_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='sandbox',
            new_name='is_sandbox',
        ),
    ]
