# Generated by Django 5.2.4 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_rename_sandbox_apikey_is_sandbox'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='authenticat_organiz_c9a805_idx',
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('organization', 'key_type', 'is_sandbox')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'key_type', 'is_sandbox'], name='authenticat_organiz_ce81f0_idx'),
        ),
    ]
