# Generated by Django 5.2.4 on 2025-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_apikey_authenticat_organiz_c9a805_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
