# Generated by Django 5.2.4 on 2025-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_user_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
