# Generated by Django 5.2.4 on 2025-08-27 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wallet_id', models.CharField(max_length=100)),
                ('created_by', models.EmailField(max_length=254)),
                ('currency', models.CharField(max_length=3)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
