# Generated by Django 5.2.4 on 2025-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_ledger_balance_alter_wallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('funding', 'Funding')], default='unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
