# Generated by Django 5.2.4 on 2025-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_event_transaction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
