# Generated by Django 5.2.4 on 2025-09-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_invitation_status'),
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='authentication.organization'),
        ),
    ]
