# Generated by Django 5.2.4 on 2025-09-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_meter_organization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
