# Generated by Django 5.2.4 on 2025-09-12 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_utilitycost'),
        ('wallet', '0003_wallet_ledger_balance_alter_wallet_available_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityVends',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vend_reference', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_vends', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vends', to='meter.meter')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_vends', to='wallet.transaction')),
                ('utility_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vends', to='meter.utilitycost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
