# Generated by Django 5.2.4 on 2025-09-12 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0005_utilityvends'),
        ('wallet', '0003_wallet_ledger_balance_alter_wallet_available_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UtilityVends',
            new_name='UtilityVend',
        ),
    ]
