# Generated by Django 5.2.4 on 2025-09-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_invitation_role_alter_membership_role'),
        ('meter', '0006_rename_utilityvends_utilityvend'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityvend',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_vends', to='authentication.organization'),
        ),
    ]
