# Generated by Django 5.2.4 on 2025-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0007_utilityvend_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilityvend',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
