# Generated by Django 5.2.4 on 2025-09-22 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_organization_is_verified_user_display_state_and_more'),
        ('meter', '0008_meter_is_sandbox_utilityvend_is_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('meter_number', 'organization'), name='unique_meter_per_organization'),
        ),
    ]
