# Generated by Django 5.2.4 on 2025-09-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0009_alter_meter_meter_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meter',
            name='unique_meter_per_organization',
        ),
    ]
