# Generated by Django 5.2.4 on 2025-09-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0010_remove_meter_unique_meter_per_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='phone_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
