# Generated by Django 5.2.4 on 2025-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0011_meter_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityvend',
            name='meter_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilityvend',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilityvend',
            name='token_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('mse', 'MSE'), ('mgtk', 'MGTK')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilityvend',
            name='token',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
