# Generated by Django 5.2.4 on 2025-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0012_utilityvend_meter_number_utilityvend_meter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityvend',
            name='token_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilityvend',
            name='token_sub_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
